name: maidxpress
description: "MaidsXpress - Professional home cleaning and maid services app. Book reliable housekeeping, deep cleaning, and maintenance services with ease."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1757591981

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add flutter_launcher_icons
  flutter_launcher_icons: ^0.14.4

  # Essential packages
  get: ^4.7.2
  intl: ^0.18.1
  get_storage: ^2.1.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  animate_do: ^4.2.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  open_filex: ^4.7.0
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Configure app icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/App_Icon.png"
  min_sdk_android: 21 # Android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image/App_Icon.png"
  windows:
    generate: true
    image_path: "assets/image/App_Icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/App_Icon.png"
  linux:
    generate: true
    image_path: "assets/image/App_Icon.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  get: ^4.7.2
  pinput: ^5.0.1
  intl: ^0.20.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  animate_do: ^4.2.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.2.0
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  calendar_date_picker2: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
